// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {fileops} from '../models';
import {index} from '../models';
import {preview} from '../models';
import {search} from '../models';

export function AddFavorite(arg1:string,arg2:string):Promise<void>;

export function BatchRename(arg1:Array<main.RenameOp>):Promise<void>;

export function CompareFolders(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.SyncDiffEntry>>;

export function CompletePath(arg1:string):Promise<Array<string>>;

export function CompressFiles(arg1:Array<string>,arg2:string):Promise<void>;

export function ConnectFTP(arg1:string,arg2:string):Promise<string>;

export function ConnectS3(arg1:string,arg2:string):Promise<string>;

export function ConnectSFTP(arg1:string,arg2:string):Promise<string>;

export function ConnectWebDAV(arg1:string,arg2:string):Promise<string>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateNewDir(arg1:string):Promise<void>;

export function CreateNewFile(arg1:string):Promise<void>;

export function CreateSymlink(arg1:string,arg2:string):Promise<void>;

export function DeleteConnectionByID(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DiffFiles(arg1:string,arg2:string):Promise<Array<main.DiffLine>>;

export function DisconnectRemote(arg1:string):Promise<void>;

export function DuplicateFile(arg1:string):Promise<string>;

export function EjectVolume(arg1:string):Promise<void>;

export function ExtractArchive(arg1:string,arg2:string):Promise<number>;

export function FormatSize(arg1:number):Promise<string>;

export function FormatTime(arg1:number):Promise<string>;

export function GetDiskUsage(arg1:string):Promise<fileops.DiskUsage>;

export function GetEntry(arg1:string):Promise<index.FileEntry>;

export function GetFavorites():Promise<Array<index.Favorite>>;

export function GetFileInfo(arg1:string):Promise<main.FileInfoDetail>;

export function GetFileTags(arg1:string):Promise<Array<string>>;

export function GetFolderSize(arg1:string):Promise<number>;

export function GetGitStatus(arg1:string):Promise<Record<string, string>>;

export function GetHomeDir():Promise<string>;

export function GetPreview(arg1:string):Promise<preview.FilePreview>;

export function GetScanProgress():Promise<index.ScanProgress>;

export function GetStats():Promise<Record<string, number>>;

export function GetThumbnail(arg1:string,arg2:number):Promise<string>;

export function GetVolumes():Promise<Array<Record<string, string>>>;

export function GitRepoRoot(arg1:string):Promise<string>;

export function GrepInDir(arg1:string,arg2:string,arg3:number):Promise<Array<main.GrepResult>>;

export function ListDir(arg1:string):Promise<Array<index.FileEntry>>;

export function ListOpenWithApps(arg1:string):Promise<Array<string>>;

export function ListSavedConnections():Promise<Array<main.ConnectionInfo>>;

export function ListWorkspaces():Promise<Array<string>>;

export function LoadKeymap():Promise<string>;

export function LoadWorkspace(arg1:string):Promise<string>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function OpenWithApp(arg1:string,arg2:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function RegexSearch(arg1:string,arg2:number):Promise<Array<search.Result>>;

export function RegexSearchInDir(arg1:string,arg2:string,arg3:number):Promise<Array<search.Result>>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function RequestICloudDownload(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveConnection(arg1:string):Promise<void>;

export function SaveKeymap(arg1:string):Promise<void>;

export function SaveWorkspace(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<search.Result>>;

export function SearchInDir(arg1:string,arg2:string,arg3:number):Promise<Array<search.Result>>;

export function ServeFileURL(arg1:string):Promise<string>;

export function ServeRemoteFileURL(arg1:string):Promise<string>;

export function SetFileTags(arg1:string,arg2:Array<string>):Promise<void>;

export function SetPermissions(arg1:string,arg2:number):Promise<void>;

export function SubstringSearch(arg1:string,arg2:number):Promise<Array<search.Result>>;

export function SubstringSearchInDir(arg1:string,arg2:string,arg3:number):Promise<Array<search.Result>>;

export function SyncFolders(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<number>;

export function Undo():Promise<string>;

export function UndoCount():Promise<number>;

export function UploadRemoteFile(arg1:string):Promise<void>;
