// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2) {
  return window['go']['main']['App']['AddFavorite'](arg1, arg2);
}

export function BatchRename(arg1) {
  return window['go']['main']['App']['BatchRename'](arg1);
}

export function CompareFolders(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareFolders'](arg1, arg2, arg3);
}

export function CompletePath(arg1) {
  return window['go']['main']['App']['CompletePath'](arg1);
}

export function CompressFiles(arg1, arg2) {
  return window['go']['main']['App']['CompressFiles'](arg1, arg2);
}

export function ConnectFTP(arg1, arg2) {
  return window['go']['main']['App']['ConnectFTP'](arg1, arg2);
}

export function ConnectS3(arg1, arg2) {
  return window['go']['main']['App']['ConnectS3'](arg1, arg2);
}

export function ConnectSFTP(arg1, arg2) {
  return window['go']['main']['App']['ConnectSFTP'](arg1, arg2);
}

export function ConnectWebDAV(arg1, arg2) {
  return window['go']['main']['App']['ConnectWebDAV'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateNewDir(arg1) {
  return window['go']['main']['App']['CreateNewDir'](arg1);
}

export function CreateNewFile(arg1) {
  return window['go']['main']['App']['CreateNewFile'](arg1);
}

export function CreateSymlink(arg1, arg2) {
  return window['go']['main']['App']['CreateSymlink'](arg1, arg2);
}

export function DeleteConnectionByID(arg1) {
  return window['go']['main']['App']['DeleteConnectionByID'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DiffFiles(arg1, arg2) {
  return window['go']['main']['App']['DiffFiles'](arg1, arg2);
}

export function DisconnectRemote(arg1) {
  return window['go']['main']['App']['DisconnectRemote'](arg1);
}

export function DuplicateFile(arg1) {
  return window['go']['main']['App']['DuplicateFile'](arg1);
}

export function EjectVolume(arg1) {
  return window['go']['main']['App']['EjectVolume'](arg1);
}

export function ExtractArchive(arg1, arg2) {
  return window['go']['main']['App']['ExtractArchive'](arg1, arg2);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function FormatTime(arg1) {
  return window['go']['main']['App']['FormatTime'](arg1);
}

export function GetDiskUsage(arg1) {
  return window['go']['main']['App']['GetDiskUsage'](arg1);
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFileTags(arg1) {
  return window['go']['main']['App']['GetFileTags'](arg1);
}

export function GetFolderSize(arg1) {
  return window['go']['main']['App']['GetFolderSize'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetPreview(arg1) {
  return window['go']['main']['App']['GetPreview'](arg1);
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function GetVolumes() {
  return window['go']['main']['App']['GetVolumes']();
}

export function GitRepoRoot(arg1) {
  return window['go']['main']['App']['GitRepoRoot'](arg1);
}

export function GrepInDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['GrepInDir'](arg1, arg2, arg3);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListOpenWithApps(arg1) {
  return window['go']['main']['App']['ListOpenWithApps'](arg1);
}

export function ListSavedConnections() {
  return window['go']['main']['App']['ListSavedConnections']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadKeymap() {
  return window['go']['main']['App']['LoadKeymap']();
}

export function LoadWorkspace(arg1) {
  return window['go']['main']['App']['LoadWorkspace'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenWithApp(arg1, arg2) {
  return window['go']['main']['App']['OpenWithApp'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RegexSearch(arg1, arg2) {
  return window['go']['main']['App']['RegexSearch'](arg1, arg2);
}

export function RegexSearchInDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegexSearchInDir'](arg1, arg2, arg3);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RequestICloudDownload(arg1) {
  return window['go']['main']['App']['RequestICloudDownload'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveKeymap(arg1) {
  return window['go']['main']['App']['SaveKeymap'](arg1);
}

export function SaveWorkspace(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkspace'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SearchInDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInDir'](arg1, arg2, arg3);
}

export function ServeFileURL(arg1) {
  return window['go']['main']['App']['ServeFileURL'](arg1);
}

export function ServeRemoteFileURL(arg1) {
  return window['go']['main']['App']['ServeRemoteFileURL'](arg1);
}

export function SetFileTags(arg1, arg2) {
  return window['go']['main']['App']['SetFileTags'](arg1, arg2);
}

export function SetPermissions(arg1, arg2) {
  return window['go']['main']['App']['SetPermissions'](arg1, arg2);
}

export function SubstringSearch(arg1, arg2) {
  return window['go']['main']['App']['SubstringSearch'](arg1, arg2);
}

export function SubstringSearchInDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubstringSearchInDir'](arg1, arg2, arg3);
}

export function SyncFolders(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncFolders'](arg1, arg2, arg3, arg4);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UndoCount() {
  return window['go']['main']['App']['UndoCount']();
}

export function UploadRemoteFile(arg1) {
  return window['go']['main']['App']['UploadRemoteFile'](arg1);
}
